local telescope = require("telescope.builtin")
vim.keymap.set("n", "<S-S><S-S>", telescope.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fg", telescope.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", telescope.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>ff", function()
  require("telescope").extensions.file_browser.file_browser()
end)
