return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      {
        "folke/ts-comments.nvim",
        event = "VeryLazy",
        enabled = vim.fn.has("nvim-0.10.0") == 1,
      },
    },
    event = "BufReadPost",
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        "lua",
        "vim",
        "vimdoc",
        "query",
        "sql",
        "markdown",
        "yaml",
        "json",
        "toml",
        "go",
        "typescript",
        "tsx",
        "javascript",
        "python",
        "bash",
        "html",
        "css",
        "csv",
        "tsv",
        "diff",
        "dockerfile",
        "editorconfig",
        "graphql",
        "hcl",
        "helm",
        "http",
        "jq",
        "mermaid",
        "nginx",
        "nix",
        "proto",
        "tmux",
      },
      sync_install = false,
      auto_install = true,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
      indent = {
        enable = true,
      },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter-context",
    opts = {},
  },
}
